// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ganyariya/itddd_go/pkg/application/service"
	service2 "github.com/ganyariya/itddd_go/pkg/domain/service"
	"github.com/ganyariya/itddd_go/pkg/infrastructure/stub"
)

// Injectors from wire.go:

func Initialize() *service.UserApplicationService {
	iUserRepository := stub.NewUserStubRepository()
	userService := service2.NewUserService(iUserRepository)
	userApplicationService := service.NewUserApplicationService(iUserRepository, userService)
	return userApplicationService
}
